--CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE MOTOS (
    ID UUID PRIMARY KEY,
    ANO INT NOT NULL,
    IDENTIFICADOR VARCHAR(100) NOT NULL, 
    MODELO VARCHAR(100) NOT NULL,
    PLACA VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE PLACAS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ANO INT NOT NULL,
    PLACA VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE TIPO_CNH (
    ID INT PRIMARY KEY,
    DESCRICAO VARCHAR(10) NOT NULL UNIQUE
);

INSERT INTO TIPO_CNH (ID, DESCRICAO) VALUES
(1, 'A'),
(2, 'B'),
(3, 'AB');

CREATE TABLE ENTREGADOR (
    ID UUID PRIMARY KEY,
    IDENTIFICADOR VARCHAR(50) NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    NUMERO_CNH VARCHAR(20) NOT NULL UNIQUE,
    TIPO_CNH INT NOT NULL,
    IMAGEM_CNH TEXT,
    CONSTRAINT fk_TIPO_CNH FOREIGN KEY (TIPO_CNH)
        REFERENCES TIPO_CNH (ID)
        ON DELETE NO ACTION
);

CREATE TABLE LOCACAO (
    ID UUID PRIMARY KEY,  
    ENTREGADOR_ID VARCHAR(50) NOT NULL,
    MOTO_ID VARCHAR(50) NOT NULL,
    VALOR_DIARIA NUMERIC(10,2),    
    VALOR_DEVOLUCAO_ATRASO NUMERIC(10,2),
    VALOR_DEVOLUCAO_ADIANTAMENTO NUMERIC(10,2),
    VALOR_TOTAL_LOCACAO NUMERIC(10,2),
    DATA_INICIO DATE NOT NULL,
    DATA_ENCERRAMENTO DATE NOT NULL,
    DATA_PREVISTA_ENCERRAMENTO DATE NOT NULL,
    DATA_DEVOLUCAO DATE,
    PLANO_LOCACAO INT NOT NULL   
);